### ISSUE TITLE
Please add License

### ISSUE THREAD

**Issue by tarmath** [opaque-systems/sequencefile#11]
Hello!

What is the license for this module? 

And (depending on given license) would contributions to fix some bugs be welcome?

Thanks!

**Comment by chester-leung** [comment]
Hi @tarmath, thanks for your interest in this. We're adding the Apache 2.0 license to this, please see #12.

Contributions are definitely welcome!

**Comment by tarmath** [comment]
Much appreciated!
Also wondering if you had by any chance planned on publishing the package to PyPI at some point?

**Comment by chester-leung** [comment]
@tarmath we did not plan on doing so in the immediate future, but can definitely add it to the roadmap if it will be useful to you :) 

We had thought of this repo as being only useful to us, but happy to publish it to PyPI if it's useful to others as well.
